SzCoreItems = {
    water = { label = 'Víz', weight = 500, stack = true, close = true, usable = true },
    sandwich = { label = 'Szendvics', weight = 350, stack = true, close = true, usable = true },
    bandage = { label = 'Kötszer', weight = 150, stack = true, close = true, usable = true },
    medkit = { label = 'Elsősegélycsomag', weight = 1200, stack = true, close = true, usable = true },
    phone = { label = 'Telefon', weight = 300, stack = false, close = false, usable = true },
    radio = { label = 'Rádió', weight = 450, stack = false, close = false, usable = true },
    vehicle_key = { label = 'Járműkulcs', weight = 50, stack = false, close = false, usable = false },
    weapon_pistol = { label = 'Pisztoly', weight = 1200, stack = false, close = true, usable = true, weapon = 'WEAPON_PISTOL' },
    ammo_9mm = { label = '9mm lőszer', weight = 12, stack = true, close = false, usable = false },
    lockpick = { label = 'Zárfeltörő', weight = 80, stack = true, close = true, usable = true },
    advancedlockpick = { label = 'Fejlett zárfeltörő', weight = 120, stack = true, close = true, usable = true },
    repairkit = { label = 'Javítókészlet', weight = 1600, stack = true, close = true, usable = true },
    advancedrepairkit = { label = 'Fejlett javítókészlet', weight = 2600, stack = true, close = true, usable = true },
    tirekit = { label = 'Kerékjavító készlet', weight = 900, stack = true, close = true, usable = true },
    cleaningkit = { label = 'Járműtisztító készlet', weight = 700, stack = true, close = true, usable = true },
    beer = { label = 'Sör', weight = 500, stack = true, close = true, usable = true },
    vodka = { label = 'Vodka', weight = 500, stack = true, close = true, usable = true },
    whiskey = { label = 'Whiskey', weight = 500, stack = true, close = true, usable = true },
    joint = { label = 'Joint', weight = 40, stack = true, close = true, usable = true },
    painkillers = { label = 'Fájdalomcsillapító', weight = 80, stack = true, close = true, usable = false },
    firstaid = { label = 'Trauma elsősegély', weight = 900, stack = true, close = true, usable = true },
}