CREATE TABLE IF NOT EXISTS szcore_accounts (license varchar(96) NOT NULL,display_name varchar(96) NOT NULL DEFAULT 'Unknown',created_at timestamp NOT NULL DEFAULT current_timestamp(),last_seen timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(license)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_characters (
 id bigint unsigned NOT NULL AUTO_INCREMENT,license varchar(96) NOT NULL,citizenid varchar(24) NOT NULL,slot tinyint unsigned NOT NULL,firstname varchar(32) NOT NULL,lastname varchar(32) NOT NULL,birthdate date NOT NULL,gender varchar(12) NOT NULL DEFAULT 'male',nationality varchar(16) NOT NULL DEFAULT 'HU',cash bigint NOT NULL DEFAULT 0,bank bigint NOT NULL DEFAULT 0,crypto bigint NOT NULL DEFAULT 0,dirty bigint NOT NULL DEFAULT 0,job varchar(48) NOT NULL DEFAULT 'unemployed',job_grade smallint unsigned NOT NULL DEFAULT 0,job_duty tinyint(1) NOT NULL DEFAULT 0,gang varchar(48) NOT NULL DEFAULT 'none',gang_grade smallint unsigned NOT NULL DEFAULT 0,metadata longtext NOT NULL,position longtext NOT NULL,permissions longtext NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),last_seen timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(id),UNIQUE KEY ux_szcore_citizenid(citizenid),UNIQUE KEY ux_szcore_license_slot(license,slot),KEY ix_szcore_license(license),KEY ix_szcore_job_duty(job,job_duty),CONSTRAINT fk_szcore_character_account FOREIGN KEY(license) REFERENCES szcore_accounts(license) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_character_groups (citizenid varchar(24) NOT NULL,group_type enum('job','gang') NOT NULL,name varchar(48) NOT NULL,grade smallint unsigned NOT NULL DEFAULT 0,duty tinyint(1) NOT NULL DEFAULT 0,is_primary tinyint(1) NOT NULL DEFAULT 0,created_at timestamp NOT NULL DEFAULT current_timestamp(),updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(citizenid,group_type,name),KEY ix_szcore_groups_lookup(group_type,name,grade),CONSTRAINT fk_szcore_groups_character FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_money_ledger (id bigint unsigned NOT NULL AUTO_INCREMENT,citizenid varchar(24) NOT NULL,account varchar(32) NOT NULL,amount bigint NOT NULL,balance bigint NOT NULL,reason varchar(128) NOT NULL DEFAULT 'unknown',created_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id),KEY ix_szcore_ledger_citizen(citizenid,created_at),CONSTRAINT fk_szcore_ledger_character FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_financial_accounts (account_id varchar(96) NOT NULL,account_type varchar(32) NOT NULL,owner_id varchar(96) DEFAULT NULL,label varchar(96) NOT NULL,balance bigint NOT NULL DEFAULT 0,allow_negative tinyint(1) NOT NULL DEFAULT 0,metadata longtext NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(account_id),KEY ix_szcore_fin_owner(account_type,owner_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_account_transactions (id bigint unsigned NOT NULL AUTO_INCREMENT,account_id varchar(96) NOT NULL,amount bigint NOT NULL,reason varchar(128) NOT NULL,actor varchar(96) DEFAULT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id),KEY ix_szcore_account_tx(account_id,created_at),CONSTRAINT fk_szcore_tx_account FOREIGN KEY(account_id) REFERENCES szcore_financial_accounts(account_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_storage (namespace varchar(64) NOT NULL,storage_key varchar(96) NOT NULL,scope varchar(24) NOT NULL DEFAULT 'global',owner_id varchar(96) NOT NULL DEFAULT '',value longtext NOT NULL,expires_at timestamp NULL DEFAULT NULL,updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(namespace,storage_key,scope,owner_id),KEY ix_szcore_storage_exp(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_societies (name varchar(48) NOT NULL,label varchar(96) NOT NULL,society_type varchar(24) NOT NULL DEFAULT 'job',account_id varchar(96) NOT NULL,metadata longtext NULL,PRIMARY KEY(name),UNIQUE KEY ux_szcore_soc_account(account_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_society_members (society varchar(48) NOT NULL,citizenid varchar(24) NOT NULL,grade smallint unsigned NOT NULL DEFAULT 0,role varchar(48) DEFAULT NULL,permissions longtext NULL,joined_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(society,citizenid),KEY ix_szcore_soc_grade(society,grade),CONSTRAINT fk_szcore_soc_member_char FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE,CONSTRAINT fk_szcore_soc_member_soc FOREIGN KEY(society) REFERENCES szcore_societies(name) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_inventories (inventory_id varchar(96) NOT NULL,owner_type varchar(24) NOT NULL,owner_id varchar(96) NOT NULL,max_slots smallint unsigned NOT NULL DEFAULT 40,max_weight int unsigned NOT NULL DEFAULT 120000,metadata longtext NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(inventory_id),KEY ix_szcore_inv_owner(owner_type,owner_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_inventory_items (inventory_id varchar(96) NOT NULL,slot smallint unsigned NOT NULL,item varchar(64) NOT NULL,amount int unsigned NOT NULL DEFAULT 1,metadata longtext NULL,PRIMARY KEY(inventory_id,slot),KEY ix_szcore_inv_item(inventory_id,item),CONSTRAINT fk_szcore_item_inv FOREIGN KEY(inventory_id) REFERENCES szcore_inventories(inventory_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_bills (id bigint unsigned NOT NULL AUTO_INCREMENT,issuer_citizenid varchar(24) DEFAULT NULL,target_citizenid varchar(24) NOT NULL,society varchar(48) DEFAULT NULL,amount bigint NOT NULL,label varchar(128) NOT NULL,status enum('unpaid','paid','cancelled') NOT NULL DEFAULT 'unpaid',created_at timestamp NOT NULL DEFAULT current_timestamp(),paid_at timestamp NULL DEFAULT NULL,PRIMARY KEY(id),KEY ix_szcore_bills_target(target_citizenid,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_vehicles (id bigint unsigned NOT NULL AUTO_INCREMENT,citizenid varchar(24) NOT NULL,plate varchar(16) NOT NULL,model varchar(64) NOT NULL,vehicle_type varchar(24) NOT NULL DEFAULT 'automobile',props longtext NOT NULL,garage varchar(48) NOT NULL DEFAULT 'legion',state enum('stored','out','impounded') NOT NULL DEFAULT 'stored',fuel decimal(5,2) NOT NULL DEFAULT 100,engine decimal(8,2) NOT NULL DEFAULT 1000,body decimal(8,2) NOT NULL DEFAULT 1000,mileage decimal(12,2) NOT NULL DEFAULT 0,finance longtext NULL,insurance longtext NULL,last_position longtext NULL,impound_fee bigint NOT NULL DEFAULT 0,impound_reason varchar(128) DEFAULT NULL,impounded_at timestamp NULL DEFAULT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(id),UNIQUE KEY ux_szcore_vehicle_plate(plate),KEY ix_szcore_vehicle_owner_state(citizenid,state),CONSTRAINT fk_szcore_vehicle_char FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_vehicle_keys (vehicle_id bigint unsigned NOT NULL,citizenid varchar(24) NOT NULL,key_type enum('owner','shared','temporary') NOT NULL DEFAULT 'shared',expires_at timestamp NULL DEFAULT NULL,PRIMARY KEY(vehicle_id,citizenid),KEY ix_szcore_keys_citizen(citizenid),CONSTRAINT fk_szcore_key_vehicle FOREIGN KEY(vehicle_id) REFERENCES szcore_vehicles(id) ON DELETE CASCADE,CONSTRAINT fk_szcore_key_char FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_appearance (citizenid varchar(24) NOT NULL,appearance longtext NOT NULL,updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(citizenid),CONSTRAINT fk_szcore_appearance_char FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_outfits (id bigint unsigned NOT NULL AUTO_INCREMENT,citizenid varchar(24) NOT NULL,name varchar(64) NOT NULL,appearance longtext NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),PRIMARY KEY(id),KEY ix_szcore_outfit_owner(citizenid),CONSTRAINT fk_szcore_outfit_char FOREIGN KEY(citizenid) REFERENCES szcore_characters(citizenid) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_queue_priorities (identifier varchar(96) NOT NULL,priority int NOT NULL DEFAULT 0,reason varchar(128) DEFAULT NULL,expires_at timestamp NULL DEFAULT NULL,PRIMARY KEY(identifier)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_audit_log (id bigint unsigned NOT NULL AUTO_INCREMENT,action varchar(64) NOT NULL,actor varchar(96) NOT NULL,target varchar(96) DEFAULT NULL,data longtext NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id),KEY ix_szcore_audit_action(action,created_at),KEY ix_szcore_audit_actor(actor,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS szcore_schema_migrations (version int NOT NULL,name varchar(128) NOT NULL,applied_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


ALTER TABLE szcore_characters ADD COLUMN IF NOT EXISTS permissions longtext NULL AFTER position;
UPDATE szcore_characters SET permissions='[]' WHERE permissions IS NULL OR permissions='';
CREATE TABLE IF NOT EXISTS szcore_bans (id bigint unsigned NOT NULL AUTO_INCREMENT,identifier varchar(96) NOT NULL,reason varchar(255) NOT NULL,banned_by varchar(96) DEFAULT NULL,expires_at timestamp NULL DEFAULT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id),KEY ix_szcore_bans_identifier(identifier,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE szcore_characters ADD COLUMN IF NOT EXISTS dirty bigint NOT NULL DEFAULT 0 AFTER crypto;

ALTER TABLE szcore_vehicles ADD COLUMN IF NOT EXISTS vehicle_type varchar(24) NOT NULL DEFAULT 'automobile' AFTER model;

ALTER TABLE szcore_vehicles ADD COLUMN IF NOT EXISTS impound_fee bigint NOT NULL DEFAULT 0 AFTER last_position;
ALTER TABLE szcore_vehicles ADD COLUMN IF NOT EXISTS impound_reason varchar(128) DEFAULT NULL AFTER impound_fee;
ALTER TABLE szcore_vehicles ADD COLUMN IF NOT EXISTS impounded_at timestamp NULL DEFAULT NULL AFTER impound_reason;
